name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Specify the custom runner labels
    runs-on: 
      group: default

    steps:
      # Step 1: Checkout the codes
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js 20.9.0 f(update from 16.x)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        
      - name: Run Build
        run: npm run build

      - name: Run Start
        run: npm run start

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build the Docker image
      - name: Build Docker image
        run: docker build -t jl115/type-test -f Dockerfile .

      # Step 8: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push jl115/type-test
